### PR TITLE
Change tab-height to 40px

### PR DESCRIPTION
**Pull request by davidcelis**
This tweak is just my opinion, but the tabs seem quite tall; there is a lot of vertical whitespace above and below the file name. I played around with it a bit locally and found 40px to be more reasonable. I figured I'd just contribute back and see what you think. Nice theme!

### CODE REVIEW

**Comment by heyvito** [comment]
:+1:

**Comment by ciarand** [comment]
:+1:

**Comment by scott-riley** [comment]
I met you in the middle and went for 48px ;) I'm personally a fan of tabs with a bit more breathing room but tightening them up a bit was a nice improvement, thanks!

**Comment by davidcelis** [comment]
Thanks for the compromise! :wink:

**Pull request closed without merging**
